### ISSUE TITLE
Background issue

### ISSUE THREAD

**Issue by Aiz4u** [harbassan/spicetify-galaxy#36]
My library and friend activities background is black not transparent

**Comment by williwoo** [comment]
have this same issue, creator told me it should be fixed in a few days

**Comment by harbassan** [comment]
yep its fixed now, give it a couple of hours or so to update

**Comment by Satanarious** [comment]
Does this work with Library X?

**Comment by EILLOxX** [comment]
how do it update? it's shpwing the same for me and my profile is all the way on the right instead of on the left and the buttions to change the wallpaper are missing just a black background screen. 
![image](https://github.com/harbassan/spicetify-galaxy/assets/128436412/4a3fac31-d67f-4b05-a921-c62aeac3a443)

**Comment by EILLOxX** [comment]
It's been fixed now, I got the update.

**Comment by williwoo** [comment]
> 

yeah me too thanks for fixing @harbassan
